apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-node-service
  template:
    metadata:
      labels:
        app: users-node-service
    spec:
      containers:
      - name: users-node-service
        image: users-node-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: users-node-service
spec:
  selector:
    app: users-node-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
